### ISSUE TITLE
Prepend $PATH with node_modules/.bin

### ISSUE THREAD

**Issue by sapegin** [sapegin/shipit#2]

**Comment by aerth** [comment]
okay to close this?

**Comment by sapegin** [comment]
It doesn’t matter if people use it for Node or not but for people who use it’ll make life easier.

**Comment by empjustine** [comment]
Since `npm@5.2.0`, the recommended way of running non-global commands of node packages is `npx ${command}`.

Under lower versions of `npm`, the [`npm-run-script`](https://docs.npmjs.com/cli/run-script) is the recommended way of running non-global commands as it automatically adds `node_modules/.bin` to the `${PATH}`.

**Comment by sapegin** [comment]
> Since npm@5.2.0, the recommended way of running non-global commands of node packages is npx ${command}.

Is it documented anywhere?

**Comment by empjustine** [comment]
The blog post on Medium is basically the only "official documentation" available.

https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

It is adopted as a recommended way of calling Node.js package module binaries for [Babel](https://babeljs.io/docs/setup/), [Webpack](https://webpack.js.org/guides/getting-started/) and [Electron](https://electronjs.org/docs/tutorial/quick-start), among other smaller modules.

**Comment by sapegin** [comment]
Sounds good!
